### ISSUE TITLE
issue with disable custom field

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/enhanced-woocommerce-mautic-integration#11]
os: window11
wp: 5.8.2
wc: 5.9.0
path: setting
description: disable custom field is not working
![image](https://user-images.githubusercontent.com/86113814/143022220-78acc1c0-7ae0-4394-b6fc-74de582a32e0.png)

**Comment by pranjalshukla-cedcoss** [comment]
Issue fixed.

**Comment by prateek-cedcoss** [comment]
there is still some issue as I show you

**Comment by pranjalshukla-cedcoss** [comment]
Resolved for all type of custom fields.

**Comment by prateek-cedcoss** [comment]
fix
