### ISSUE TITLE
issue with the disable Custom fields on 'last order payment date' and 'mode of payment'

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/enhanced-woocommerce-mautic-integration#12]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.2.2
path: setting
description: when we disable last order payment date and mode of payment in disable custom field, then also data get sync to the mautic.

**Comment by pranjalshukla-cedcoss** [comment]
Resolved.

**Comment by prateek-cedcoss** [comment]
fix
