### ISSUE TITLE
QA/phpcs issues

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/enhanced-woocommerce-mautic-integration#13]
QA file:
https://docs.google.com/document/d/1UmUX3PNWkbI6Tl-sl_K2BUBTFJP6q17eYKj8Xwlu9Dg/edit?usp=sharing

phpcs: file
[enhanced-woocommerce-mautic-integration-xml.zip](https://github.com/Makewebbetter/enhanced-woocommerce-mautic-integration/files/7632135/enhanced-woocommerce-mautic-integration-xml.zip)

**Comment by pranjalshukla-cedcoss** [comment]
QA issues resolved.

Phpcs issues also resolved, but these some issues are not resolvable:
1. Class file names should be based on the class name with "class-" prepended.
2. Object property "$isPublished" is not in valid snake_case format, try "$is_published".

Please ignore these issues.

**Comment by prateek-cedcoss** [comment]
fix
